[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/site/*"
  status = 200
  to = "/.netlify/functions/site/:splat"

echo Building Functions.
